-- @description Scan for silence in selected item (install 5 scripts)
-- @version 1.1
-- @author Scott Chesworth
-- @about
--   Run the Configure scan for silence script to set peak and duration of the silences you want to find.
--
--   Use any combination of the other scripts to move to the beginning or end of previous or next detected silences in the selected item.
--
--   Scanning begins from the edit cursor if stopped, or the play cursor if playing.
--
--   If the project is playing when you run the scripts, it will continue doing so after the edit cursor has been moved.
-- @provides
--   [main] Scan for Silence/Scott_Move to beginning of next silence in selected item.lua
--   [main] Scan for Silence/Scott_Move to beginning of previous silence in selected item.lua
--   [main] Scan for Silence/Scott_Move to end of next silence in selected item.lua
--   [main] Scan for Silence/Scott_Move to end of previous silence in selected item.lua
--   [main] Scan for Silence/Scott_Configure scan for silence.lua
